### ISSUE TITLE
Exporter Keeps Shutting Down

### ISSUE THREAD

**Issue by Coldstorageunit** [tedder/miner_exporter#8]
You guys still seeing these issues? My node exporter will run for about 5 minutes before it shuts down. These are the errors showing up in the logs:

Traceback (most recent call last):
  File "/opt/app/miner_exporter.py", line 327, in <module>
    stats()
  File "<decorator-gen-1>", line 2, in stats
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "/opt/app/miner_exporter.py", line 126, in stats
    collect_balance(docker_container,miner_facts['address'],hotspot_name_str)
  File "/opt/app/miner_exporter.py", line 148, in collect_balance
    api_validators = safe_get_json(f'https://testnet-api.helium.wtf/v1/validators/{addr}')
  File "/opt/app/miner_exporter.py", line 130, in safe_get_json
    ret = requests.get(url)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='testnet-api.helium.wtf', port=443): Max retries exceeded with url: /v1/validators/1ZaCvhW663DFrchg3i5xvgXnH2en4QKc2BTTzPpMQLD7r7SQFci (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc421132370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by tedder** [comment]
Thanks. I'm catching that error now. Just do a `pull` and you should be able to get it.

In the future [use triple-backticks to quote the error message](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code), it's more readable.

**Comment by Coldstorageunit** [comment]
Tried a pull the other day but get a permission error for some reason. Thanks for the triple tick tip as well!

**Comment by tedder** [comment]
lemme know if you have any problems with pulls or anything else. always good to improve this.

**Comment by Coldstorageunit** [comment]
Yesterday it mentioned login issues. Tried the pull just now and get this:

```
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by tedder** [comment]
ah yeah, that's probably from too many requests. I recommend using ghcr.io instead of dockerhub, because dockerhub has pretty strict limits. The error from just now seems like you have DNS or other network issues.

**Comment by Coldstorageunit** [comment]
Getting the login error again. 

```Error response from daemon: pull access denied for silly_wozniak, repository does not exist or may require 'docker login': denied: requested access to the resource is denied```

I'm thinking I'm probably not doing something correctly. I'm not using GHCR.io or docker hub, to my knowledge, I'm just running the command in terminal:

```docker pull [container name]```

and then getting that login error.

**Comment by tedder** [comment]
what's the container name you are trying to pull? you can DM me on discord if you want.
